config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  resources :main
  resources :user do
    collection do
      post 'login'
      get 'login'
      get 'activate/:activation_token' => 'users#activate', as: :activate
      get 'recover'
    end
  end
  resources :jobseeker, controller: 'user'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, :polymorphic => true
  validates  :state, :state => true
  def self.us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end
  def self.states_full_name
    names = []
    self.us_states.each do |full_name, small_name|
      names << full_name
    end
    names
  end
  def self.states_small_name
    names = []
    self.us_states.each do |full_name, small_name|
      names << small_name
    end
    names
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :addresses, :as => :addressable
  has_many :employers

  has_many :jobs

  validates :phone, :phone => true
  validates :ein, :presence => true,
                  :einNumber => true
  validates :email, :email => true
  validates :website, :url => true
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  acts_as :user
  belongs_to :company
  has_many :jobs

  validates :phone, :phone => true
  validates :company, :presence => true
end

app/models/job.rb
class Job < ActiveRecord::Base

  validates :employer, :presence => true
  validates :company, :presence => true
  validates :title, length: {in: 1..150},
                    :presence => true
  validates :description, :presence => true,
                          length: {minimum: 20}

  belongs_to :employer
  belongs_to :company

  has_many :job_skills
  has_many :skills, :through => :job_skills

  has_many :required_skills, -> { where job_skills: { required: true } }, through: :job_skills, class_name: 'Skill', source: :skill
  has_many :nice_to_have_skills, -> { where job_skills: { required: false } }, through: :job_skills, class_name: 'Skill', source: :skill


  def short_description
    "#{self.description[0..30]}#{'...' if self.description.length > 30}"
  end
end

app/models/job_seeker.rb
class JobSeeker < ActiveRecord::Base
  acts_as :user
end

app/models/job_seeker_status.rb
class JobSeekerStatus < ActiveRecord::Base
end

app/models/job_skill.rb
class JobSkill < ActiveRecord::Base
  belongs_to :job
  belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :job_skills
  has_many :jobs, :through => :job_skills

  validates :name, :presence => true,
                   length: {in: 1..100}
  validates :description, :presence => true,
                          length: {in: 1..500}
end

app/models/user.rb
class User < ActiveRecord::Base
  actable

  validates :email, :email => true,
                    :uniqueness => true,
                    :presence => true

  validates :password, :length => {minimum: 8}

  has_secure_password

  after_create :after_creation

  def activated?
    self.activation_token == nil
  end

  private
    def generate_activation_token
      self.activation_token = self.id.to_s + (0...16).map { (65 + rand(26)).chr }.join
      save
    end
    def after_creation
      generate_activation_token
      UserMailer.activation(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActionController::ParameterMissing, :with => :missing_parameters
  rescue_from ActionController::RoutingError, :with => :error_render_method

  def missing_parameters
    respond_to do |type|
      type.all {
        flash[:error] = 'Invalid form'
        redirect_to :back
      }
      type.all  { render :nothing => true, :status => 400 }
    end
    true
  end

  def error_render_method
    respond_to do |type|
      type.all  { render :template => 'errors/error_404', :status => 404 }
    end
    true
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    getUser
    respond_to do |format|
      format.html {render partial: 'new', layout: 'modal'}
    end
  end

  def create
    getUser
    @user = @user_class.new
    @user.update_attributes filter_params
    respond_to do |format|
      if @user.save
        flash[:success] = 'Registration successful, you will receive one email to active your account!'
        #format.html {redirect_to root_path}
        format.all { render json: {:url => root_path}, status: :ok }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js   { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  def login
    respond_to do |format|
      format.html do
        @modal_title = 'Login'
        render partial: 'login', layout: 'modal'
      end
    end
  end

  private
  def getUser
    case request.original_fullpath
      when /jobseeker/
        @user = JobSeeker.new
        @url = jobseeker_index_path
        @user_class = JobSeeker
        @params_key = :job_seeker
    end
  end
  def filter_params
    params.require(@params_key).permit(:first_name,
                                       :last_name,
                                       :email,
                                       :password,
                                       :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def list_jobs
    @jobs ||= Job.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end

  def logged_in?
    current_user != nil
  end
end

app/views/jobs/_list.html.haml
%div{:class => 'container'}
  %div{:class => 'row'}
    %h3 List of job opportunities
  %div{:class => 'row'}
    %div{:class => 'panel panel-default'}
      %table{:class => 'table table-bordered', 'data-card-view' => 'true', 'data-height' => '299' }
        %thead
          %tr
            %td
              Title
            %td
              Employer
            %td
              Description
            %td
              More information
        %tbody
          - list_jobs.each do |job|
            %tr
              %td
                = job.title
              %td
                = job.company.name
              %td
                = job.short_description
              %td
                - if logged_in?
                  Some information
                - else
                  You need to login for more information

app/views/layouts/_footer.html.haml
%footer{:class => 'footer'}
  %div{:class => 'container'}
    %center
      = "@ Met Plus #{Date.today.year}"

app/views/layouts/_menu.html.haml
%nav{:class => 'menu navbar navbar-default navbar-fixed-top'}
  %div{:class => 'container'}
    %div{:class => 'navbar-header'}
      %a{:class => 'navbar-brand', :href => '#'} MetPlus
    %div{:id=>'navbar', :class => 'navbar-collapse collapse'}
      %ul{:class => 'nav navbar-nav'}
        %li{:class => 'menu-item'}
          %a{:href => root_path} Home
        %li{:class => 'menu-item'}
          %a{:href => '#'} Jobs
        %li{:class => 'menu-item'}
          %a{:href => '#'} About
        %li{:class => 'menu-item'}
          %a{:href => '#'} Contact
        %li
      %ul{:class => 'nav navbar-nav navbar-right'}
        - if !logged_in?
          %li
            %div{:class => 'button-menu'}
              = link_to 'Log In', login_user_index_path, :role => 'button', :class => 'btn btn-default btn-xs', :id => 'login_button'
          %li{:id => 'register-button'}
            %div{:class => 'button-menu'}
              = link_to 'New user', new_jobseeker_path, :role => 'button', :class => 'btn btn-default btn-xs', :id => 'registration_button'
        - else
          %li
            = "Hello, #{link_to current_user.first_name, user_path(current_user)}"
          %li
            = link_to 'Logout', root_path

app/views/layouts/_modal.html.haml
%div{:id => 'modal', :class => 'modal-popup'}
  %header{:class => 'popupHeader'}
    %span{:class => 'header_title'}
      = @modal_title
    %span{:class => 'modal_close'}
      %button{:class => 'close', 'data-dismiss' => 'modal', 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
  %section{:class => 'popupBody'}
    = yield

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title  MetPlus
    = csrf_meta_tags
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css'
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'
  %body
    = render partial: 'layouts/menu'
    %div{:id => 'loading', :style => "background: url('#{asset_path 'spinner.gif'}') no-repeat center center; display:none;"}
    %div{:class => 'content container'}
      %div{:class => 'row', :id => 'messages'}
        %div{:class => 'container'}
          - flash.each do |key, value|
            %div{:class => "alert alert-#{key}"}
              = value
      %div{:class => 'row'}
        = yield
    = render 'layouts/footer'

app/views/main/index.html.haml
%h1 MetPlus
= render partial: 'jobs/list'
= yield

app/views/user/_form.html.haml
.form_div
  = form_for(@user, :remote=> true, :url => @url, html: {role: :form, 'data-model' => @params_key}) do |f|
    .form_field
      = f.label :first_name
      = f.text_field :first_name, :placeholder => 'John'
      .help-block
    .form_field
      = f.label :last_name
      = f.text_field :last_name, :placeholder => 'Doe'
      .help-block
    .form_field
      = f.label :email
      = f.text_field :email, :placeholder => 'johndoe@mail.com'
      .help-block
    .form_field
      = f.label :password
      = f.password_field :password
      .help-block
        %p The password must have at least 8 characters
    .form_field
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      .help-block
    - if @user.instance_of? JobSeeker
      .form_field
        = f.label :job_search_status
        = select_tag :job_seeker_status,
          options_from_collection_for_select(JobSeekerStatus.all,
                                             'id',
                                             'value',
                                             @user.job_seeker_status_id)
    - if new
      = button_tag 'Register', class: 'btn btn-primary submit-button right', type: 'submit', autocomplete: 'off',
                  :data => {:disable_with => "<i class='fa fa-cog fa-spin'></i> Registering...".html_safe}
    - else
      = button_tag 'Save', class: 'btn btn-primary submit-button right', type: 'submit',autocomplete: 'off',
                  :data => {:disable_with => "<i class='fa fa-cog fa-spin'></i> Saving...".html_safe}

app/views/user/_login.html.haml
= form_for User.new, :url => login_user_index_path, :html => {:class => 'login_form', :id => 'login_form'} do |f|
  .form_field
    = f.label :email
    %br
    = f.text_field :email, :placeholder => 'Email Address'
  .form_field
    = f.label :password
    %br
    = f.text_field :password, :placeholder => 'Account Password'
  = button_tag 'Login', class: 'btn btn-primary submit-button', type: 'submit',autocomplete: 'off',
                  :data => {:disable_with => "<i class='fa fa-cog fa-spin'></i> Login...".html_safe}
%a{href: recover_user_index_path, class: 'btn btn-primary'} Forgot password

app/views/user/_new.html.haml
%h2 Register user
= render partial: 'form', locals: {new: true}
= yield

app/views/user/edit.html.haml
%h2 Update information
= render partial: 'form', locals: {new: false, user: @user, url: @url}
= yield

app/views/user/new.html.haml
%h2 Register user
= render partial: 'form', locals: {new: true}
= yield

app/views/user/show.html.haml
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>